### ISSUE TITLE
Event store SQL scripts should be re-runnable + Create a method named CreateDatabaseObjects in AdoNetEventStoreDatabaseMigrator for creating at the first time all tables required for Event Sourcing.

### ISSUE THREAD

**Issue by VCuzmin** [osstotalsoft/nbb#105]
Event store SQL scripts should be re-runnable + Create a method named CreateDatabaseObjects in AdoNetEventStoreDatabaseMigrator for creating at the first time all tables required for Event Sourcing.
This way there would be no need to execute all scrips manually.

**Comment by oncicaradupopovici** [comment]
done in v5
