### ISSUE TITLE
Model NBB.Effect types with structs instead of classes and benchmark the results

### ISSUE THREAD

**Issue by oncicaradupopovici** [osstotalsoft/nbb#154]
The NBB.Effect family of types (Effect, Pure, Impure,  EffectFnSeq, etc) is modeled via reference types which puts a lot of presure on the GC.
We should be able to cut off a lot of managed memory allocations using value types.
Be carefull with value types, as they get boxed when casted to interface types, we should avoid polymorhism in those cases.

**Comment by oncicaradupopovici** [comment]
See Ms recomandations https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/choosing-between-class-and-struct

**Comment by fraliv13** [comment]
Struct types do not support inheritance and it cannot be done in a type safe manner.
