### ISSUE TITLE
Introduce Projections in ES

### ISSUE THREAD

**Issue by VasileCuzmin** [osstotalsoft/nbb#239]
Projections are a primary pattern you’ll likely use with Event Sourcing. It’s the answer to the most common question I get about event sourcing which is: How do you build out UI? If you have to replay all the events in an event stream to get to the current state, isn’t that very inefficient when it comes to displaying in a UI or reporting?

The answer, depending on your situation, could be yes. It could be very inefficient to have to replay an entire event stream to get to the current state.

This is where projections come in.

As a starter you can take a look at https://github.com/bolicd/practicalcqrs - it's simple and on point. It can be improved more, though. 
Yet, there are a few open-source projects that use projections such as EventStore, Axon or EventFlow.

**Comment by oncicaradupopovici** [comment]
@VasileCuzmin NBB already provides a built-in solution for authoring read-model projections, inspired by ELM model-view-update pattern, take a look here https://github.com/osstotalsoft/nbb/tree/master/src/Projections/NBB.ProjectR

**Comment by VasileCuzmin** [comment]
It was in front of my eyes all this time... I didn't see it. Then I will take a look for sure. I will close the issue now. 
Thanks! 

> @VasileCuzmin NBB already provides a built-in solution for authoring read-model projections, inspired by ELM model-view-update pattern, take a look here https://github.com/osstotalsoft/nbb/tree/master/src/Projections/NBB.ProjectR

It was in front of my eyes all this time... I didn't see it. Then I will take a look for sure. I will close the issue now. 
Thanks!
