### ISSUE TITLE
Hello from an OpenFaaS core contributor!

### ISSUE THREAD

**Issue by burtonr** [osstotalsoft/nbb#3]
This is not really an issue, I just wasn't able to find any other way to contact anyone on this project.

I discovered this while searching through NuGet.org for existing OpenFaaS packages. I am one of the core contrtibutors to the OpenFaaS project and would like to hear more about how you're using the project. 

Please feel free to contact me directly. My email is on my profile. Alternatively, please consider joining the OpenFaaS community on [Slack](https://docs.openfaas.com/community/#slack-workspace)

Thank you

**Comment by oncicaradupopovici** [comment]
Hi,

Thanks for letting us know!

We have been playing (some time ago) with a server-less Mediator implemented over OpenFaas.
There were some problems related to dotnet startup and our infrastructure that relies havily on DI containers witch slowed down the application startup.

We are more microservices oriented, although, we haven't abandoned (completely) the  _holy grail of infinite scaling_
