### ISSUE TITLE
process manager - duplicate definitions

### ISSUE THREAD

**Issue by dorinsimionescu** [osstotalsoft/nbb#32]
One can call services.AddProcessManagerDefinition multiple times or can have multiple definitions for the same type. Now, the runtime dies with 
`"Message of type XXX could not be processed due to the following exception System.InvalidOperationException: Sequence contains more than one element at System.Linq.ThrowHelper.ThrowMoreThanOneElementException()
  at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable1 source)
  at NBB.ProcessManager.Runtime.ProcessExecutionCoordinator.Invoke"`

Desired behaviour: similar with a DI container's Build process, the program should check for duplicate definitions after startup is complete (maybe also introduce a build function) and throw a more programmer friendly exception like "multiple definitions have been loaded for the same.. ".

However, it is to be discussed if multiple definitions for the same event should be supported, eg maybe I want to have a fork coming out of the same event. Example: an user is created, I want to start an email sending process and also start a flow where I check the person against an fraud internal database.

**Comment by oncicaradupopovici** [comment]
It's the same issue with services.AddMvc() or services.AddDbContext ...
