### ISSUE TITLE
Event store - multiple calls

### ISSUE THREAD

**Issue by dorinsimionescu** [osstotalsoft/nbb#33]
one can call this code multiple times:
`services.AddEventStore()
                .WithNewtownsoftJsonEventStoreSeserializer()
                .WithAdoNetEventRepository();`

Result: 
`System.Data.SqlClient.SqlException (0x80131904): WrongExpectedVersion     at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)  at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)     at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)     at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)     at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)     at System.Data.SqlClient.SqlCommand.CompleteAsyncExecuteReader()     at System.Data.SqlClient.SqlCommand.EndExecuteNonQueryInternal(IAsyncResult asyncResult)     at System.Data.SqlClient.SqlCommand.EndExecuteNonQuery(IAsyncResult asyncResult)     at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)  --- End of stack trace from previous location where exception was thrown ---     at NBB.EventStore.AdoNet.AdoNetEventRepository.AppendEventsToStreamExpectedVersionAsync(String streamId, IList`1 eventDescriptors, Int32 expectedVersion, CancellationToken cancellationToken)  ClientConnectionId:e86fba0e-c407-4228-96fb-65e85c8cb171  Error Number:50000,State:1,Class:16     --- End of inner exception stack trace ---     at NBB.EventStore.AdoNet.AdoNetEventRepository.AppendEventsToStreamExpectedVersionAsync(String streamId, IList`1 eventDescriptors, Int32 expectedVersion, CancellationToken cancellationToken)     at NBB.EventStore.AdoNet.AdoNetEventRepository.AppendEventsToStreamAsync(String streamId, IList`1 eventDescriptors, Nullable`1 expectedVersion, CancellationToken cancellationToken)     at NBB.EventStore.EventStore.AppendEventsToStreamAsync(String stream, IEnumerable`1 events, Nullable`1 expectedVersion, CancellationToken cancellationToken)     at NBB.ProcessManager.Runtime.Persistence.InstanceDataRepository.Save[TData](Instance`1 instance, CancellationToken cancellationToken) in ...`

Desired behaviour: some validation on this topic.

**Comment by oncicaradupopovici** [comment]
It's the same issue with services.AddMvc() or services.AddDbContext ...
