### ISSUE TITLE
WithAdoNetEventRepository - override

### ISSUE THREAD

**Issue by dorinsimionescu** [osstotalsoft/nbb#35]
support custom connection string override.
example: 

            services.AddEventStore()
                .WithNewtownsoftJsonEventStoreSeserializer()
                .WithAdoNetEventRepository(o=> {o.ConnectionString= ""; o.TopicPrefix = "";} );

**Comment by oncicaradupopovici** [comment]
Should be implemented using the options pattern: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-5.0

**Comment by fraliv13** [comment]
It is already implemented using the options pattern. It can be configured like this:

```csharp
  services.Configure<EventStoreOptions>(opts =>
  {
      opts.ConnectionString = "";
  });
```
