### ISSUE TITLE
ParseInternal - the God Method phenomenon

### ISSUE THREAD

**Issue by VCuzmin** [osstotalsoft/nbb#37]
A "God Method" is a method that does way too many processes in the system and has grown beyond all logic to become The Method That Does Everything. When need for new processes increases suddenly some programmers realize: why should I create a new method for each processe if I can only add an if. 
A large and complex method should be split in smaller methods, or even one or several classes can be created for that. 
Large switch…case structures might be refactored through the help of a set of types that implement a common interface, the interface polymorphism playing the role of the switch cases tests. 
Unit Tests can help: write tests for each method before extracting it to ensure you don't break functionality.

**Comment by oncicaradupopovici** [comment]
This method has only one responsability: parses a TypeInfo
