### ISSUE TITLE
ExcelDataExport.Export, GetCommandHandler, CsvDataExport.Export, ParseInternal has too many local variables

### ISSUE THREAD

**Issue by VCuzmin** [osstotalsoft/nbb#38]
To refactor such method and increase code quality and maintainability, certainly you'll have to split the method into several smaller methods or even create one or several classes to implement the logic.

**Comment by oncicaradupopovici** [comment]
The NBB.Export packages were moved to https://github.com/osstotalsoft/nbb-extras
