### ISSUE TITLE
HttpFormatter, BodyParser, HeaderParser might be turned into a static type

### ISSUE THREAD

**Issue by VCuzmin** [osstotalsoft/nbb#39]
A stateless class or structure might be turned into a static type. 
Such class or structure is a stateless collection of pure functions, that doesn't act on any this object data. Such collection of pure functions is better hosted in a static class. Doing so simplifies the client code that doesn't have to create an object anymore to invoke the pure functions.

**Comment by oncicaradupopovici** [comment]
Totally agree! But this repo does not contain and have never contained this classes. Was this issue ment for NBB?
