### ISSUE TITLE
ICommand, IMessage are empty. Are these marker interfaces???

### ISSUE THREAD

**Issue by VCuzmin** [osstotalsoft/nbb#40]
Interfaces define members that provide a behavior or usage contract. The functionality that is described by the interface can be adopted by any type, regardless of where the type appears in the inheritance hierarchy. A type implements an interface by providing implementations for the members of the interface. An empty interface does not define any members. Therefore, it does not define a contract that can be implemented. 
If this identification will occur at run time, the correct way to accomplish this is to use a custom attribute. Use the presence or absence of the attribute, or the properties of the attribute, to identify the target types. If the identification must occur at compile time, then it is acceptable to use an empty interface.

**Comment by oncicaradupopovici** [comment]
yes they were! now they're gone
