### ISSUE TITLE
Process manager - state should not be contrained to beeing a struct

### ISSUE THREAD

**Issue by dorinsimionescu** [osstotalsoft/nbb#45]
Currently, the state in process manager is a struct. It should be a class.

Using a struct is a way to insure the state does not have behaviour. 

However, the "framework" should not be THAT opinionated and should allow the programmer to have the responsibility of its own code.

**Comment by oncicaradupopovici** [comment]
Totally agree now in the context of record types as refence immutable types

**Comment by oncicaradupopovici** [comment]
done in v5.x
